config/routes.rb
Eatcpcks::Application.routes.draw do
  resources :links

  resources :recipes

  devise_for :users

  resources :photos do
    resources :tags, :albums
  end

  resources :tags do
    resources :photos
  end

  resources :albums do
    resources :photos
  end

  resources :films do
    resources :photos
  end

  resources :cameras do
    resources :photos
  end
  match'feed'=>'photos#feed', :format => 'atom'
  root :to => "Photos#last"
   match ':static' => 'static#show'

  

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  
  cattr_reader :per_page
  @@per_page = 36
  
  has_many :ingredients
  has_many :steps
  has_and_belongs_to_many :photos
  accepts_nested_attributes_for :ingredients, :allow_destroy => true
  accepts_nested_attributes_for :steps, :allow_destroy => true
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_filter :is_user!, :except => [:show, :index] 
  # GET /recipes
  # GET /recipes.xml
  def index
@recipes = Recipe.paginate(:page => params[:page], :order => 'id DESC')
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @recipes }
    end
  end

  # GET /recipes/1
  # GET /recipes/1.xml
  def show
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @recipe }
    end
  end

  # GET /recipes/new
  # GET /recipes/new.xml
  def new
    @recipe = Recipe.new
    @photos = Photo.find(:all)
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @recipe }
    end
  end

  # GET /recipes/1/edit
  def edit
    @recipe = Recipe.find(params[:id])
    @photos = Photo.find(:all)
  end

  # POST /recipes
  # POST /recipes.xml
  def create
    @recipe = Recipe.new(params[:recipe])

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to(@recipe, :notice => 'Recipe was successfully created.') }
        format.xml  { render :xml => @recipe, :status => :created, :location => @recipe }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @recipe.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /recipes/1
  # PUT /recipes/1.xml
  def update
    @recipe = Recipe.find(params[:id])
    @recipe.photos = []
    respond_to do |format|
      if @recipe.update_attributes(params[:recipe])
        format.html { redirect_to(@recipe, :notice => 'Recipe was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @recipe.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.xml
  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to(recipes_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
  
end

app/views/recipes/_form.html.erb
<div class="fav"><%= image_tag "logo.png" %></div>
<%= form_for(setup_recipe(@recipe)) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :difficulty %><br />
    <%= f.text_field :difficulty %>
  </div>
  <div class="field">
    <%= f.label :preparation %><br />
    <%= f.text_field :preparation %>
  </div>
  <div class="field">
    <%= f.label :cookingTime %><br />
    <%= f.text_field :cookingTime %>
  </div>
<div>
	<% f.fields_for :ingredients do |ingredient_form| %>
	<%= render "ingredient_fields", :f => ingredient_form%>
	      
	    <% end %>
	<%= link_to_add_fields "Add ingredient", f, :ingredients%>
	</div>
	<div>
<% f.fields_for :steps do |step_form| %>
      <%= render "step_fields", :f => step_form %>
    <% end %>
	<%= link_to_add_fields 'Add step', f, :steps%>
</div>

<div class="formThumbs">
	<%= f.label :photos %><br />
<% for photo in Photo.find(:all) %>

  <%= check_box_tag "recipe[photo_ids][]", photo.id, @recipe.photos.include?(photo) %>
<%if @recipe.photos.include?(photo)%>
  <%= image_tag(photo.image.url(:square), :border =>0, :class => 'thumb selected', :onclick=>"checkImage($(this));") %>
<%else%>
<%= image_tag(photo.image.url(:square), :border =>0, :class => 'thumb', :onclick=>"checkImage($(this));") %>
<%end%>
<% end %>
</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipes/_ingredient_fields.html.erb
<p>
    <div>
      <%= f.label :name, 'Ingredient:' %>
      <%= f.text_field :name %>
	  <%= f.label :quantity, 'Quantity:' %>
	  <%= f.text_field :quantity %>
    </div>

    <% unless f.object.new_record? %>
      <div>
        <%= link_to_remove_fields "Remove ingredient", f %>

      </div>
    <% end %>
  </p>

app/views/recipes/_step_fields.html.erb
<p>
    <div>
      <%= f.label :desc, 'Step:' %>
      <%= f.text_field :desc %>
    </div>

    <% unless f.object.new_record? %>
      <div>
        <%= link_to_remove_fields "Remove step", f %>
      </div>
    <% end %>
  </p>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<h1>Recipes</h1>
	<% i=0%>
	<%- if @recipes.empty?%>
	<p class="later">It's in the oven!</p>
	<%-end%>
<% @recipes.each do |recipe| %>
<%- if !recipe.photos.empty?  || user_signed_in? -%>
	<div class="category grid_4 <%- if i==0 -%>alpha<%-end-%> <%- if i==5 -%>omega<%-end-%>">
		<span class="leftAlign"><%= recipe.name %></span>
		<%= link_to image_tag(randomMediumPicture(recipe), :border =>0),:controller =>'recipes', :action => 'show', :id => recipe %>
		<%- if user_signed_in? -%>
		<div class="triangle right"></div>
		<span class="rightAlign"><%= link_to 'p', edit_recipe_path(recipe), :class=>"icon" %> <%= link_to 't', recipe, :confirm => 'Delete this?', :method => :delete, :class=>"icon" %></span>
		
		<%- end -%>
		<%-i = i+1 -%>
		<%- if i==6 -%>
		<%-i=0 end-%>
	</div><%-end-%>
<% end %>
<%= will_paginate @recipes %>

<%= link_to image_tag('add.png'), new_recipe_path, :class =>'add' if user_signed_in?%>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>
<%i=0%>

<div class="steps  grid_4 alpha">
	
	<%- if user_signed_in?  -%>
	<div class="triangle right"></div>
	<span class="rightAlign"><%= link_to 'p', edit_recipe_path(@recipe), :class=>"icon"%> <%= link_to 't', @recipe, :confirm => 'Delete this?', :method => :delete , :class=>"icon"%></span>
	<%edit = true%>
	<%-end-%>
<p>
	  <b>Name:</b>
	  <%= @recipe.name %><br/>
	  <b>Difficulty:</b>
	  <%= @recipe.difficulty %><br/>
	  <b>Preparation:</b>
	  <%= @recipe.preparation %><br/>
	  <b>Cookingtime:</b>
	  <%= @recipe.cookingTime %><br/>
</p>
</div>
	
	<div class="steps grid_9">
		<ul>
	<% @recipe.ingredients.each do |ingredient| %>
		<% line = ingredient.quantity+ " of " + ingredient.name if ingredient.quantity != ''%>
		<% line =  ingredient.name if ingredient.quantity == ''%>
	  <li><%=line%></li>
	
	<% end %>
	</ul>
	</div>
	<div class="steps grid_10 omega">
		<ol>
	<% @recipe.steps.each do |step| %>
	
	<li>  <%=step.desc%></li>

	<% end %>
	</ol>
	</div>
	<div class="grid_24 alpha omega">
	<% @recipe.photos.each do |photo| %>
	<div class="category grid_4 <%- if i==0 -%>alpha<%-end-%> <%- if i==5 -%>omega<%-end-%>">
	  <%= link_to image_tag(photo.image.url(:square), :border =>0, :class => 'thumb'),:controller =>'photos', :action => 'show', :id => photo %>
	</div>
	<%-i = i+1 -%>
	<%- if i==6 -%>
	<%-i=0 end-%>
	<% end %>
	</div>

<%= link_to image_tag('bak.png'), recipes_path, :class =>'add'%>