config/routes.rb
Eatcpcks::Application.routes.draw do
  resources :links

  resources :recipes

  devise_for :users

  resources :photos do
    resources :tags, :albums
  end

  resources :tags do
    resources :photos
  end

  resources :albums do
    resources :photos
  end

  resources :films do
    resources :photos
  end

  resources :cameras do
    resources :photos
  end
  match'feed'=>'photos#feed', :format => 'atom'
  root :to => "Photos#last"
   match ':static' => 'static#show'

  

end

app/models/film.rb
class Film < ActiveRecord::Base
  
  cattr_reader :per_page
  @@per_page = 36
  
  has_many :photos
  def fullName()
    brand+" "+name
  end
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_filter :is_user!, :except => [:show, :index] 
  # GET /films
  # GET /films.xml
  def index
    
@films = Film.paginate(:page => params[:page], :order => 'id DESC')
  if (!is_user?)
    @films.delete_if {|x| x.photos.empty? }
  end
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @films }
    end
  end

  # GET /films/1
  # GET /films/1.xml
  def show
    @film = Film.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @film }
    end
  end

  # GET /films/new
  # GET /films/new.xml
  def new
    @film = Film.new
    @photos = Photo.find(:all)
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @film }
    end
  end

  # GET /films/1/edit
  def edit
    @film = Film.find(params[:id])
    @photos = Photo.find(:all)
  end

  # POST /films
  # POST /films.xml
  def create
    @film = Film.new(params[:film])

    respond_to do |format|
      if @film.save
        format.html { redirect_to(@film, :notice => 'Film was successfully created.') }
        format.xml  { render :xml => @film, :status => :created, :location => @film }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @film.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /films/1
  # PUT /films/1.xml
  def update
    @film = Film.find(params[:id])

    respond_to do |format|
      if @film.update_attributes(params[:film])
        format.html { redirect_to(@film, :notice => 'Film was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @film.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /films/1
  # DELETE /films/1.xml
  def destroy
    @film = Film.find(params[:id])
    @film.destroy

    respond_to do |format|
      format.html { redirect_to(films_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/films_helper.rb
module FilmsHelper
  def filmFormat()
      ['120mm','35mm', 'polaroid']
    end
    def filmIso()
        ['50','100', '200', '400', '800']
      end
end

app/views/films/_form.html.erb
<div class="fav"><%= image_tag "logo.png" %></div>
<%= form_for(@film) do |f| %>
  <% if @film.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@film.errors.count, "error") %> prohibited this film from being saved:</h2>

      <ul>
      <% @film.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type %><br />
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :format %><br />
    <%= f.select(:format, filmFormat )%>
  </div>
  <div class="field">
    <%= f.label :iso %><br />
    <%= f.select(:iso, filmIso )%>
  </div>
  <div class="field">
    <%= f.label :brand %><br />
    <%= f.text_field :brand %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
<div class="formThumbs">
	<%= f.label :photos %><br />
<% for photo in @photos %>

  <%= check_box_tag "film[photo_ids][]", photo.id, @film.photos.include?(photo) %>
<%if @film.photos.include?(photo)%>
  <%= image_tag(photo.image.url(:square), :border =>0, :class => 'thumb selected', :onclick=>"checkImage($(this));") %>
<%else%>
<%= image_tag(photo.image.url(:square), :border =>0, :class => 'thumb', :onclick=>"checkImage($(this));") %>
<%end%>
<% end %>
</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/films/edit.html.erb
<h1>Editing film</h1>

<%= render 'form' %>

<%= link_to 'Show', @film %> |
<%= link_to 'Back', films_path %>

app/views/films/index.html.erb
<h1>Films</h1>
	<% i=0%>
<% @films.each do |film| %>
	<div class="category grid_4 <%- if i==0 -%>alpha<%-end-%> <%- if i==5 -%>omega<%-end-%>">
		<span class="leftAlign"><%= film.fullName %></span>
		<%= link_to image_tag(randomMediumPicture(film), :border =>0),:controller =>'films', :action => 'show', :id => film %>
		<%- if user_signed_in? -%>
		<div class="triangle right"></div>
		<span class="rightAlign"><%= link_to 'p', edit_film_path(film), :class=>"icon" %> <%= link_to 't', film, :confirm => 'Delete this?', :method => :delete, :class=>"icon" %></span>
		
		<%- end -%>
		<%-i = i+1 -%>
		<%- if i==6 -%>
		<%-i=0 end-%>
	</div><%-end-%>
<%= will_paginate @films %>

<%= link_to image_tag('add.png'), new_film_path, :class =>'add' if user_signed_in?%>

app/views/films/new.html.erb
<h1>New film</h1>

<%= render 'form' %>

<%= link_to 'Back', films_path %>

app/views/films/show.html.erb
<p id="notice"><%= notice %></p>
<div class="category desc grid_4 alpha">
	<p>
 	  <b>Type:</b>
	  <%= @film.type %><br/>
	  <b>Format:</b>
	  <%= @film.format %><br/>
	  <b>Brand:</b>
	  <%= @film.brand %><br/>
	  <b>Name:</b>
	  <%= @film.name %><br/>
	  <b>Description:</b>
	  <%= @film.description %>
	</p>
</div>
	<%-i=1-%>
	<%edit = false%>
	<% @film.photos.each do |photo| %>
	<div class="category grid_4 <%- if i==0 -%>alpha<%-end-%> <%- if i==5 -%>omega<%-end-%>">
		<%- if user_signed_in? && !edit -%>
		<div class="triangle right"></div>
		<span class="rightAlign"><%= link_to 'p', edit_film_path(@film), :class=>"icon"%> <%= link_to 't', @film, :confirm => 'Delete this?', :method => :delete , :class=>"icon"%></span>
		<%edit = true%>
		<%-end-%>
	  <%= link_to image_tag(photo.image.url(:square), :border =>0, :class => 'thumb'),:controller =>'photos', :action => 'show', :id => photo %>
	</div>
	<%-i = i+1 -%>
	<%- if i==6 -%>
	<%-i=0 end-%>
	<% end %>

<%= link_to image_tag('bak.png'), films_path, :class =>'add'%>