config/routes.rb
Eatcpcks::Application.routes.draw do
  resources :links

  resources :recipes

  devise_for :users

  resources :photos do
    resources :tags, :albums
  end

  resources :tags do
    resources :photos
  end

  resources :albums do
    resources :photos
  end

  resources :films do
    resources :photos
  end

  resources :cameras do
    resources :photos
  end
  match'feed'=>'photos#feed', :format => 'atom'
  root :to => "Photos#last"
   match ':static' => 'static#show'

  

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  
  cattr_reader :per_page
  @@per_page = 36
  
  has_and_belongs_to_many :photos
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_filter :is_user!, :except => [:show, :index] 
  # GET /tags
  # GET /tags.xml
  def index
    if (params[:photo_id])
      @tags = Photo.find(params[:photo_id]).tags
    else
      @tags = Tag.paginate(:page => params[:page], :order => 'id DESC')
    end
    if (!is_user?)
      @tags.delete_if {|x| x.photos.empty? }
    end
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @tags }
    end
  end

  # GET /tags/1
  # GET /tags/1.xml
  def show
    @tag = Tag.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @tag }
    end
  end

  # GET /tags/new
  # GET /tags/new.xml
  def new
    @tag = Tag.new
    @photos = Photo.find(:all)
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @tag }
    end
  end

  # GET /tags/1/edit
  def edit
    @tag = Tag.find(params[:id])
    @photos = Photo.find(:all)
  end

  # POST /tags
  # POST /tags.xml
  def create
    @tag = Tag.new(params[:tag])

    respond_to do |format|
      if @tag.save
        format.html { redirect_to(@tag, :notice => 'Tag was successfully created.') }
        format.xml  { render :xml => @tag, :status => :created, :location => @tag }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @tag.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tags/1
  # PUT /tags/1.xml
  def update
    @tag = Tag.find(params[:id])

    respond_to do |format|
      if @tag.update_attributes(params[:tag])
        format.html { redirect_to(@tag, :notice => 'Tag was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @tag.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.xml
  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to(tags_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<div class="fav"><%= image_tag "logo.png" %></div>
<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
<div class="formThumbs">
	<%= f.label :photos %><br />
<% for photo in @photos %>

  <%= check_box_tag "tag[photo_ids][]", photo.id, @tag.photos.include?(photo) %>
<%if @tag.photos.include?(photo)%>
  <%= image_tag(photo.image.url(:square), :border =>0, :class => 'thumb selected', :onclick=>"checkImage($(this));") %>
<%else%>
<%= image_tag(photo.image.url(:square), :border =>0, :class => 'thumb', :onclick=>"checkImage($(this));") %>
<%end%>
<% end %>
</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<h1>Tags</h1>
<% i=0%>
<% @tags.each do |tag| %>
		<%- if !tag.photos.empty?  || user_signed_in? -%>
	<div class="category grid_4 <%- if i==0 -%>alpha<%-end-%> <%- if i==5 -%>omega<%-end-%>">
		<span class="leftAlign"><%= tag.name %></span>
		<%= link_to image_tag(randomMediumPicture(tag), :border =>0),:controller =>'tags', :action => 'show', :id => tag %>
		<%- if user_signed_in? -%>
		<div class="triangle right"></div>
		<span class="rightAlign"><%= link_to 'p', edit_tag_path(tag), :class=>"icon"%> <%= link_to 't', tag, :confirm => 'Delete this?', :method => :delete, :class=>"icon" %></span>
		<%-end-%>
	</div>
	<%-i = i+1 -%>
	<%- if i==6 -%>
	<%-i=0 end-%>
	<%-end-%>
	<% end %>


<%= link_to image_tag('add.png'), new_tag_path, :class =>'add' if user_signed_in?%>

app/views/tags/new.html.erb
<h1>New tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>
<div class="category desc grid_4 alpha">
<p>
  <b>Name:</b>
  <%= @tag.name %>
  <b>Description:</b>
  <%= @tag.description %>
</p>
</div>
	<%-i=1-%>
	<%edit = false%>
	<% @tag.photos.each do |photo| %>
	<div class="category grid_4 <%- if i==0 -%>alpha<%-end-%> <%- if i==5 -%>omega<%-end-%>">
		<%- if user_signed_in? && !edit -%>
		<div class="triangle right"></div>
		<span class="rightAlign"><%= link_to 'p', edit_tag_path(@tag), :class=>"icon"%> <%= link_to 't', @tag, :confirm => 'Delete this?', :method => :delete , :class=>"icon"%></span>
		<%edit = true%>
		<%-end-%>
	  <%= link_to image_tag(photo.image.url(:square), :border =>0, :class => 'thumb'),:controller =>'photos', :action => 'show', :id => photo %>
	</div>
	<%-i = i+1 -%>
	<%- if i==6 -%>
	<%-i=0 end-%>
	<% end %>

<%= link_to image_tag('bak.png'), tags_path, :class =>'add'%>