config/routes.rb
Eatcpcks::Application.routes.draw do
  resources :links

  resources :recipes

  devise_for :users

  resources :photos do
    resources :tags, :albums
  end

  resources :tags do
    resources :photos
  end

  resources :albums do
    resources :photos
  end

  resources :films do
    resources :photos
  end

  resources :cameras do
    resources :photos
  end
  match'feed'=>'photos#feed', :format => 'atom'
  root :to => "Photos#last"
   match ':static' => 'static#show'

  

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  
  cattr_reader :per_page
  @@per_page = 36
  
  attr_accessor :tagslist
  belongs_to :camera
  belongs_to :film
  has_and_belongs_to_many :tags
  has_and_belongs_to_many :albums
  has_attached_file :image,
    :styles => { :medium => "300x300>", :thumb => "100x100>", :square => "300x300#" , :web =>"1000x1000>"},
    :storage => :googlestorage,
    :bucket => "eatcpcks",
    :path => ":attachment/:id/:style.:extension",
    :google_storage_credentials => "#{RAILS_ROOT}/config/storage.yml"
    
    # Paperclip Validations
    validates :name, :presence => true
    validates_attachment_presence :image
    #validates_attachment_content_type :image, :content_type => ['image/jpeg', 'image/pjpeg', 'image/jpg']
    validates_attachment_size :image, :less_than => 10.megabytes,
        :message => 'filesize must be less than 10 MegaBytes'
      validates_attachment_content_type :image, :content_type => [ 'image/jpeg' ],
                    :message => 'file must be of filetype .jpeg'

      def isPublished?
        if (self.published == nil || self.published == false)
          false
        else
          true
        end
      end
      def set_mime_type(data)
        data.content_type = MIME::Types.type_for(data.original_filename)[0].to_s
        self.image = data
      end
      def previous
        self.class.first(:conditions => ["id > ?", id], :order => "id asc")
      end

      def next
        self.class.first(:conditions => ["id < ?", id], :order => "id desc")
        
      end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_filter :is_user!, :except => [:feed,:show, :index, :last]
  before_filter :getLists, :only => [:new, :create, :edit, :update]
  require "kconv"
  
  # GET /photos
  # GET /photos.xml
  def index
    if (params[:camera_id])
      @photos = Photo.find_all_by_camera_id(params[:camera_id])
    elsif (params[:film_id])
      @photos = Photo.find_all_by_film_id(params[:film_id])
    elsif (params[:album_id])
      @photos = Album.find(params[:album_id]).photos
    else
      @photos = Photo.paginate(:page => params[:page], :order => 'id DESC')
    end
    if (!is_user?)
      @photos.delete_if {|x| !x.isPublished? }
    end
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @photos }
      format.json  { render :json => @photos }
    end
  end
  
  #GET /
  def last
    @lastPhotos = Photo.find(:all, :order=>'id DESC', :limit => 10)
  end
  
  
  def feed
    @photos = Photo.all
    respond_to do |format|
      format.atom
    end
  end
  # GET /photos/1
  # GET /photos/1.xml
  def show
    @photo = Photo.find(params[:id])
    if (!is_user? && !@photo.isPublished?)
        raise ActiveRecord::RecordNotFound 
    end
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @photo }
      format.json  { render :json => @photo }
    end
  end
  
  
  def getLists
    @cameras = Camera.all
    @films = Film.all
  end
  # GET /photos/new
  # GET /photos/new.xml
  def new
    @photo = Photo.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @photo }
      format.json  { render :json => @photo }
    end
  end

  # GET /photos/1/edit
  def edit
    @photo = Photo.find(params[:id])
    
  end

  # POST /photos
  # POST /photos.xml
  def create
    logger.debug "Post should be valid: #{request.headers["Content-Type"]}"
      if (params[:photo])
        params[:photo].image.each do |image|
          photo = Photo.new
          photo.set_mime_type(image)
          photo.name = image.original_filename
          photo.published = false
          photo.save
        end

        respond_to do |format|

          format.html { head :ok }
          format.xml  { render :xml => @photo, :status => :created, :location => @photo }
          format.json  { render :json => @photo, :status => :created, :location => @photo }

        end
      else
        @photo = Photo.new
        @photo.set_mime_type(params[:image])
        @photo.name = params[:image].original_filename
        @photo.published = false
        respond_to do |format|
          if @photo.save
            format.html { head :ok }
            format.xml  { render :xml => @photo, :status => :created, :location => @photo }
            format.json  { render :json => @photo, :status => :created, :location => @photo }
          else
            format.html { render :action => "new" }
            format.xml  { render :xml => @photo.errors, :status => :unprocessable_entity }
            format.json  { render :json => @photo.errors, :status => :unprocessable_entity}
          end
        end
      end
   
  end

  # PUT /photos/1
  # PUT /photos/1.xml
  def update
    @photo = Photo.find(params[:id])
    @tags = params[:photo][:tagslist].split(',')
    @tags.each{|tagName|
      @tag = Tag.find_by_name(tagName);
      if @tag == nil
        @tag = Tag.new
        @tag.name = tagName
        @tag.save
      end
      @photo.tags << @tag
    }
    @beforeUpdatePublished= @photo.isPublished?
    respond_to do |format|
      if @photo.update_attributes(params[:photo])
        if (@photo.isPublished? && !@beforeUpdatePublished) 
          postToTwitter("New picture on #doyoueatcupcakes ! : "+ request.url)
        end
        format.html { redirect_to(@photo, :notice => 'Photo was successfully updated.') }
        format.xml  { head :ok }
        format.json  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @photo.errors, :status => :unprocessable_entity }
        format.json  { render :json => @photo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.xml
  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to(photos_url) }
      format.xml  { head :ok }
      format.json  { head :ok }
      format.js { render :nothing => true }
    end
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<div class="fav"><%= image_tag "logo.png" %></div>
<%= form_for @photo, :html => { :multipart => true } do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= f.file_field :image, :multiple =>"multiple" %>


<div class="actions">
  <%= f.submit %>
</div>
<script type="text/javascript">
<%- session_key = Rails.application.config.session_options[:key] -%>
$(function () {
    
  var uploadify_script_data = {};
  
  // Fetch the CSRF meta tag data
  var csrf_token = $('meta[name=csrf-token]').attr('content');
  var csrf_param = $('meta[name=csrf-param]').attr('content');
  
  // Now associate the data in the config, encoding the data safely
  uploadify_script_data[csrf_param] = encodeURIComponent(encodeURIComponent(csrf_token));
  
  // Associate the session information
  uploadify_script_data['<%= session_key %>'] = '<%= cookies[session_key] %>';
  
  $('#photo_image').uploadify({
    script : '/photos',
	uploader  : '/javascripts/uploadify.swf',
	multi: true,
	fileDataName: 'image',
	cancelImg: '/images/cancel.png',
    scriptData : uploadify_script_data
  }); 
$('#photo_submit').click(function(event){
event.preventDefault();
$('#photo_image').uploadifyUpload();
});  
});

</script>
<% end %>

app/views/photos/_form_edit.html.erb
<div class="fav"><%= image_tag "logo.png" %></div>
<%= form_for @photo, :html => { :multipart => true } do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<%= image_tag @photo.image.url(:thumb) %>
<div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :taken %><br />
    <%= f.date_select :taken %>
  </div>
  <div class="field">
    <%= f.label :xpro %><br />
    <%= f.check_box :xpro %>
  </div>
  <div class="field">
    <%= f.label :camera %><br />
    <%= f.collection_select( :camera_id, @cameras, :id, :fullName, :prompt => 'Please select camera') %>
  </div>
  <div class="field">
    <%= f.label :film %><br />
    <%= f.collection_select( :film_id, @films, :id, :fullName, :prompt => 'Please select film') %>
  </div>
<div>
	<%= f.label :tags %><br />
<% for tag in Tag.find(:all) %>

  <%= check_box_tag "photo[tag_ids][]", tag.id, @photo.tags.include?(tag) %>
  <%= tag.name %><br/>
<% end %><br/>
<%= f.label :tagslist%><br />
<%= f.text_field :tagslist%>
<div>
	<%= f.label :albums %><br />
<% for album in Album.find(:all) %>

  <%= check_box_tag "photo[album_ids][]", album.id, @photo.albums.include?(album) %>
  <%= album.name %><br/>
<% end %>
</div>


<div class="field">
    <%= f.label :published %><br />
    <%= f.check_box :published %>
  </div>
<div class="actions">
  <%= f.submit %>
</div>

<% end %>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render 'form_edit' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<h1>Photos</h1>
<% i=0 %>
<% @photos.each do |photo| %>
	<div class=" grid_4 <%- if i==0 -%>alpha<%- end -%> <%- if i==5 -%>omega<%- end -%> category">
		<%#<div class="triangle left"></div>%>
		<span class="leftAlign"><%= link_to photo.name, photo %></span>
		<%= link_to image_tag(photo.image.url(:square), :border =>0), photo %>
		<%- if user_signed_in? -%>
		<div class="triangle right"></div>
		<span class="rightAlign"><%= link_to 'p', edit_photo_path(photo), :class=>"icon" %> <%= link_to 't', photo, :confirm => 'Delete this picture?', :method => :delete, :remote=>true, :class=> "icon delete-icon" %> <%-if !photo.isPublished?-%> <a class="icon">L</a><%-end-%></span>
		<%-end-%>
		<%- i = i+1 -%>
		<%- if i==6 -%>
		<%- i=0 end-%>
		
	</div>
<% end %>
<%= will_paginate @photos %>
<%= link_to image_tag('add.png'), new_photo_path, :class =>'add' if user_signed_in?%>

app/views/photos/last.html.erb
<h1>Why?</h1>
<style>

</style>
<script type="text/javascript">
$(window).load(function() {
    $('#slider').nivoSlider({
	        effect:'fade', //Specify sets like: 'fold,fade,sliceDown'
	        slices:15,
	        animSpeed:500, //Slide transition speed
	        pauseTime:3000,
	        startSlide:0, //Set starting Slide (0 index)
	        directionNav:true, //Next & Prev
	        directionNavHide:true, //Only show on hover
	        controlNav:true, //1,2,3...
	        controlNavThumbs:false, //Use thumbnails for Control Nav
	        controlNavThumbsFromRel:false, //Use image rel for thumbs
	        controlNavThumbsSearch: '.jpg', //Replace this with...
	        controlNavThumbsReplace: '_thumb.jpg', //...this in thumb Image src
	        keyboardNav:true, //Use left & right arrows
	        pauseOnHover:true, //Stop animation while hovering
	        manualAdvance:false, //Force manual transitions
	        captionOpacity:0.8, //Universal caption opacity
	        beforeChange: function(){},
	        afterChange: function(){},
	        slideshowEnd: function(){}, //Triggers after all slides have been shown
	        lastSlide: function(){}, //Triggers when last slide is shown
	        afterLoad: function(){} //Triggers when slider has loaded
	    });
});
</script>
<div id="hider" class="grid_24 alpha omega">
<div id="slider" >
<% @lastPhotos.each do |photo| %>
	<div class="slide">
		<%= link_to image_tag(photo.image.url(:web), :border =>0),photo %>
	</div>
<% end %>

</div>
</div>

<p class="faqSpace grid_18 push_3">Hey, Have you ever tried to cook some pictures? Don't eat them when they are too hot, it could hurt!</p>

app/views/photos/new.html.erb
<h1>New photo</h1>

<%= render 'form' %>
<%= %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<% content_for :title, "Do You eat cupcakes | "+@photo.name %>
<%= link_to("Previous", @photo.previous, :class => 'previous') if @photo.previous %>
<%= link_to("Next", @photo.next, :class => 'next') if @photo.next %>
<div class="photo grid_16 alpha">
	<%- if user_signed_in? -%>
<div class="triangle right"></div>

<span class="rightAlign">
	<%= link_to 'p', edit_photo_path(@photo),:class =>"icon" if user_signed_in? %> 
	<%-if !@photo.isPublished?-%> <a class="icon">L</a><%-end-%>
	
</span>
<%-end-%>
	<%= image_tag @photo.image.url(:web)%>
</div>
<span class="grid_8 omega photoDesc">
<p id="notice"><%= notice %></p>
<p>
  <span class="label">Name:</span>
  <%= @photo.name %>
</p>
<%-if (@photo.description!=nil && @photo.description!='')-%>
<p>
  <span class="label">Description:</span>
  <%= @photo.description %>
</p>
<%-end-%>
<p>
  <span class="label">Xpro:</span>
  <%-if @photo.xpro == true%>
  	&#10003;
  <%-else-%>
	&#10008;
  <%-end-%>
</p>
<%- if !@photo.camera!=nil%>
<p>
  <span class="label">Camera:</span>
<%= link_to @photo.camera.fullName, @photo.camera if( @photo.camera != nil)%>
</p>
<%-end%>
<p>
	<%- if !@photo.film!=nil%>
  <span class="label">Film:</span>
  <%= link_to @photo.film.fullName, @photo.film if( @photo.film != nil)%>
</p>
<%-end%>
<%- if !@photo.tags.empty?%>
<p>
	<span class="label">Tags:</span>
	<% @photo.tags.each do |tag| %>
		<%= link_to tag.name , tag %> 
	<% end%>
</p>
<%-end%>
<p>
<a href="http://twitter.com/share" class="twitter-share-button" data-count="horizontal" data-via="eatcpcks">Tweet</a><script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>

<script src="http://connect.facebook.net/en_US/all.js#xfbml=1"></script><fb:like href="<%=request.url%>" layout="button_count" show_faces="false" width="450"></fb:like>
</p>

</span>
<%= link_to image_tag('bak.png'), photos_path, :class =>'add'%>